language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-pip
  - sudo apt-get install -qq python-pandas
  - sudo apt-get install -y gdal-bin libgdal-dev
  - sudo apt-get install -y python-gdal
install:
  - "pip install . --no-deps"
script:
  - "raster2xyz -h"
