language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-pip
  - sudo apt-get install -y gdal-bin libgdal1h libgdal-dev
  - export CFLAGS=$(gdal-config --cflags)
install:
  - "pip install -r requirements.txt"
  - "pip install ."
script:
  - "raster2xyz -h"
